### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/trip-data-pipeline#1]
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc9 in position 6441: invalid continuation byte
```

I believe this is because the files from CMT are not in UTF-8 format, while the verifone files are. I believe this because I used [enca](https://linux.die.net/man/1/enca) to guess the encoding (although it's supposedly impossible to guess file encodings...).

```bash
enca -L none -g PPA_Trips_20150701_20150930.csv # cmt
=> 7bit ASCII characters
=>   CRLF line terminators
```

```bash
enca -L none -g query3.csv # verifone
=> Universal transformation format 8 bits; UTF-8
=>  CRLF line terminators
```

**Comment by timwis** [comment]
Someone in IRC suggested it's probably `windows-1252` encoded (common for excel produced files in western countries)

EDIT: Here's the culprit string on line 1052460 of verifone's `q2.csv`:
```
"457 Rang Des Petits-�tangs La Pr�sentation Qu�bec J0H"
```

**Comment by mjumbewu** [comment]
Seems like a reasonable guess. 0xc9 is definitely invalid UTF-8. It's curious that enca says it's valid UTF-8.

Maybe try translating the encoding with `enca` to UTF-8 and pass the result through instead. That or add something like an `--encoding` flag to the cli (`petl.fromcsv` accepts an [`encoding` parameter](http://petl.readthedocs.io/en/latest/io.html#petl.io.csv.fromcsv)). Or try to read as default (UTF-8) and, if it fails, try reading with Latin-1 or Windows-1252.

**Comment by timwis** [comment]
So it turns out the Quebec string is from verifone, not cmt. enca guesses that `q2.csv` is 7bit ascii.

I've modified `fromcsvs` to receive the other params that `petl.fromcsv` accepts (`encoding`, `errors`, `csvargs`, etc.) and will try passing `encoding='windows-1252'` to `fromcsvs`.

**Comment by timwis** [comment]
It worked!

**Comment by timwis** [comment]
For future reference here's the command I used to find the mischevious byte:

```bash
ggrep --color='auto' -n --text $'\xc9' verifone/q2.csv
```

/cc @nwebz
